# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='bookingrequest',
            name='email',
        ),
        migrations.RemoveField(
            model_name='bookingrequest',
            name='name',
        ),
        migrations.RemoveField(
            model_name='bookingrequest',
            name='phone',
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.User'),
        ),
    ]
