# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-07 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20181107_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='notes',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='number_of_people',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
