# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-09 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20181107_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.Meal'),
        ),
    ]
